### ISSUE TITLE
Add Webpack?

### ISSUE THREAD

**Issue by akabiru** [simonewebdesign/elm-new#17]
Hi @simonewebdesign Very handy tool! I think it'd be great to add webpack for a smoother build process. Been working with this workflow on https://github.com/akabiru/shufflebox-frontend and it's been a breeze so far. Would this interest you? I'd be happy to take this up.

**Comment by simonewebdesign** [comment]
Thanks for the suggestion! IMHO this tool shouldn't be concerned with the build process. Main reason is the choice can be biased, e.g. people may prefer Gulp, Brunch or other build tools over Webpack. So I think the safest bet is to point people to `elm make`, even though it's not as smooth as it should be, at least it's the official way to go.

Just to list some possibilities there's [create-elm-app](https://github.com/halfzebra/create-elm-app) and [elm-live](https://github.com/tomekwi/elm-live) which are both built on Node. Also [elm-webpack-starter](https://github.com/moarwick/elm-webpack-starter) seems to be looking for new contributors. :)

I'll close this, but feel free to continue this conversation if you feel it's worth!

**Comment by akabiru** [comment]
@simonewebdesign Makes sense. Thanks for the suggestions, I'll keep an eye out for where else I can contribute. Cheers! 🙂
